name: Sync to Maven Central
description: Syncs a release to Maven Central and waits for it to be available for use
inputs:
  jfrog-cli-config-token:
    description: 'Config token for the JFrog CLI'
    required: true
  spring-retry-version:
    description: 'The version of Spring Retry that is being synced to Central'
    required: true
  central-token-username:
    description: 'Token name for authentication with the Central Portal'
    required: true
  central-token:
    description: 'Token for authentication with the Central Portal'
    required: true

runs:
  using: composite
  steps:
    - name: Set Up JFrog CLI
      uses: jfrog/setup-jfrog-cli@7c95feb32008765e1b4e626b078dfd897c4340ad # v4.1.2
      env:
        JF_ENV_SPRING: ${{ inputs.jfrog-cli-config-token }}

    - name: Download Release Artifacts
      shell: bash
      run: jf rt download --spec ${{ format('{0}/artifacts.spec', github.action_path) }} --spec-vars 'buildName=${{ format('spring-retry-{0}', inputs.spring-retry-version) }};buildNumber=${{ github.run_number }}'

    - name: Deploy Bundle to Maven Central Portal
      uses: spring-io/central-publish-action@v0.3.0
      with:
        token-name: ${{ inputs.central-token-username }}
        token: ${{ inputs.central-token }}
        dir: central_bundle